title: "Kolt-Hasselager IF"
baseurl: "" # SÃ¦t "/khif-tribune" her, hvis github custom domain fjernes i Repo settings.
url: "https://khiftribune.dk" # Github pages default site er https://msj33.github.io
theme: minima
